development:
  :concurrency: 5
  :queues:
    - [critical, 10]
    - [active_storage_analysis, 5]
    - [default, 2]
    - [mailers, 1]
    - [active_storage_purge, 1]
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
  :queues:
    - [critical, 10]
    - [active_storage_analysis, 5]
    - [default, 2]
    - [mailers, 1]
    - [active_storage_purge, 1]

max_retries: <%= ENV.fetch("SIDEKIQ_MAX_RETRIES") { 25 } %>
